// OWNER LANE: FEATURE-AUDIO. Loudness plan for the sound catalogue. Pure data.
//
// TARGET_RMS: the intended loudness of each sound family, as the RMS (dBFS, loud part only) measured through
// the full mixing chain at the DEFAULT settings (master 0.65, sfx 1.0). Steps and mining ticks sit low, block
// breaks and the pickup pop sit in the middle, the explosion is capped by peak (≤ −6 dBFS even at max volume).
// TRIM_DB: per-sound correction measured by the 'audio-catalog' smoke scenario (offline render through the
// real graph) so each sound lands on its family target. Regenerate after changing recipes:
//   node tools/smoke.mjs --tag audio --scenario audio-catalog   ->  .tmp/audio-trim.json  (copy into TRIM_DB)

/** [regex, target RMS dBFS] - first match wins. */
export const TARGET_RMS = Object.freeze([
  [/^block\.break\./, -27], [/^block\.place\./, -29], [/^block\.land\./, -32], [/^block\.step\./, -35], [/^block\.hit\./, -37],
  [/^ui\.tick$/, -37], [/^ui\.click$/, -31], [/^ui\.(open|close|hint|error|sleep)$/, -31], [/^ui\.(success|undo|whoosh)$/, -28],
  [/^player\.levelup$/, -27], [/^player\.(hurt|bigfall|splash)$/, -28], [/^player\.(land|swim|eat|burp)$/, -32],
  [/^item\.pop$/, -29], [/^item\.drop$/, -33], [/^item\.break$/, -28],
  [/^spider\.(idle|hurt|death)$/, -31], [/^fire\.ignite$/, -31],
  [/\.step$/, -37], [/\.(idle|hurt|death)$/, -28], [/^(wolf\.bark|horse\.neigh|creeper\.hiss)$/, -28],
  [/^(wolf\.whine|wolf\.angry)$/, -30], [/^cat\.purr$/, -32],
  [/^mob\.eat$/, -33], [/^mob\.love$/, -30], [/^entity\.pop$/, -32], [/^entity\.poof$/, -31],
  [/^explosion$/, -28], [/^tnt\.fuse$/, -31], [/^water\.ambient$/, -36], [/^furnace\.crackle$/, -34],
  [/^(lava\.pop|egg\.lay|bonemeal)$/, -32], [/./, -30],
]);

/** Target RMS for a catalogue name. */
export function targetRms(name) {
  for (const [re, db] of TARGET_RMS) if (re.test(name)) return db;
  return -30;
}

/** Measured trims in dB (see header). Missing names = 0 dB. */
export const TRIM_DB = Object.freeze({
  'block.break.stone': -13.9,
  'block.place.stone': -16.5,
  'block.step.stone': -5.7,
  'block.hit.stone': -11.9,
  'block.land.stone': -16.2,
  'block.break.wood': -13,
  'block.place.wood': -17.3,
  'block.step.wood': -9.5,
  'block.hit.wood': -15.9,
  'block.land.wood': -18.6,
  'block.break.grass': -10.5,
  'block.place.grass': -14,
  'block.step.grass': -11.9,
  'block.hit.grass': -11.2,
  'block.land.grass': -16.8,
  'block.break.dirt': -6.6,
  'block.place.dirt': -10.9,
  'block.step.dirt': -2.9,
  'block.hit.dirt': -2.2,
  'block.land.dirt': -15.7,
  'block.break.gravel': -1.9,
  'block.place.gravel': -8.6,
  'block.step.gravel': -7.8,
  'block.hit.gravel': -7.9,
  'block.land.gravel': -15.4,
  'block.break.sand': -9.3,
  'block.place.sand': -11.6,
  'block.step.sand': -10,
  'block.hit.sand': -9.1,
  'block.land.sand': -16.9,
  'block.break.cloth': -11.5,
  'block.place.cloth': -13.2,
  'block.step.cloth': -8.1,
  'block.hit.cloth': -5.8,
  'block.land.cloth': -19.1,
  'block.break.glass': -8.1,
  'block.place.glass': -11.6,
  'block.step.glass': -9.2,
  'block.hit.glass': -11.1,
  'block.land.glass': -16.7,
  'block.break.snow': -3.3,
  'block.place.snow': -6.4,
  'block.step.snow': -5.6,
  'block.hit.snow': -9.1,
  'block.land.snow': -14.1,
  'block.break.metal': -14,
  'block.place.metal': -13.7,
  'block.step.metal': -8.9,
  'block.hit.metal': -12.8,
  'block.land.metal': -18.3,
  'block.break.plant': -8.3,
  'block.place.plant': -10.6,
  'block.step.plant': -8.3,
  'block.hit.plant': -8.8,
  'block.land.plant': -15.8,
  'block.break.liquid': -7.7,
  'block.place.liquid': -9.2,
  'block.step.liquid': -7.1,
  'block.hit.liquid': -6.4,
  'block.land.liquid': -15.3,
  'ui.click': -16.3,
  'ui.open': -11.1,
  'ui.close': -8.8,
  'ui.tick': -15.6,
  'ui.success': -8.4,
  'ui.whoosh': 0.9,
  'ui.error': -11.5,
  'ui.undo': -1.1,
  'ui.hint': -7.8,
  'ui.sleep': -7,
  'player.hurt': -8.5,
  'player.land': -16.2,
  'player.bigfall': -16.4,
  'player.splash': -8,
  'player.swim': -1.1,
  'player.eat': -0.3,
  'player.burp': 2.8,
  'player.levelup': -7.7,
  'item.pop': -14.7,
  'item.drop': -14.5,
  'item.break': -7.6,
  'pig.idle': -3.2,
  'pig.hurt': -1.1,
  'pig.death': 0.3,
  'pig.step': -10.8,
  'cow.idle': -2.3,
  'cow.hurt': -1.4,
  'cow.death': -0.6,
  'cow.step': -10.8,
  'sheep.idle': 0.6,
  'sheep.hurt': 2.5,
  'sheep.death': 2.2,
  'sheep.step': -10.8,
  'chicken.idle': -0.4,
  'chicken.hurt': -1.8,
  'chicken.death': -4.4,
  'chicken.step': -10.8,
  'wolf.idle': -0.7,
  'wolf.hurt': -7.3,
  'wolf.death': -12.6,
  'wolf.step': -10.8,
  'cat.idle': -3.5,
  'cat.hurt': -1,
  'cat.death': 0.9,
  'cat.step': -10.8,
  'horse.idle': 7.9,
  'horse.hurt': -6.4,
  'horse.death': -8.3,
  'horse.step': -10.8,
  'zombie.idle': 0.7,
  'zombie.hurt': 0.5,
  'zombie.death': 0.5,
  'zombie.step': -10.8,
  'skeleton.idle': 0.4,
  'skeleton.hurt': -5.9,
  'skeleton.death': -5.7,
  'skeleton.step': 0.5,
  'creeper.idle': 1,
  'creeper.hurt': -4.6,
  'creeper.death': -7.7,
  'creeper.step': -10.8,
  'spider.idle': -6.2,
  'spider.hurt': -10.7,
  'spider.death': -10,
  'spider.step': -6.3,
  'wolf.bark': -4.9,
  'wolf.whine': -11.2,
  'wolf.angry': 1.4,
  'cat.purr': -10,
  'horse.neigh': -7,
  'creeper.hiss': -9.4,
  'mob.eat': 3.7,
  'mob.love': -5.7,
  'entity.pop': -15,
  'entity.poof': -8,
  'tnt.fuse': -13.6,
  'explosion': -14,
  'door.open': -3.1,
  'door.close': -16.9,
  'chest.open': -2.2,
  'chest.close': -16.1,
  'furnace.crackle': -0.1,
  'bucket.fill': -5.2,
  'bucket.empty': -5.5,
  'fire.ignite': 0.5,
  'lava.pop': -15.7,
  'shear': -6.3,
  'bonemeal': -4.7,
  'egg.lay': -15.4,
  'water.ambient': -0.1,
});
