// OWNER: LEAD (v1.7, judge FID-8). The Nether: a small, kid-safe dimension reached through a lit obsidian frame.
// Pure constants and helpers (Node, workers, main thread). SPEC §2.8.
//
// It is not a separate world: every world keeps its Nether in a strip far to the east, x >= NETHER_EDGE, which
// the overworld can never reach (the soft world border is at most 2048 blocks from the spawn). Columns there are
// generated by world/gen_nether.js, saved like any other column, and drawn with the Nether sky (renderer), with no
// weather, no sun, moon, stars or clouds (FX), and no mob spawning (MOBS). Coordinates scale 1:8 like Java:
// overworld (x, z) <-> Nether (NETHER_X0 + x/8, z/8).

export const NETHER_X0 = 32768;           // overworld x = 0 maps here
export const NETHER_SCALE = 8;
export const NETHER_EDGE = NETHER_X0 - 4096;
/** Sea of lava up to this y (inclusive) in open caverns. */
export const NETHER_LAVA_Y = 31;
/** Fog / sky colour (0..1 RGB) and the light floor while the camera is in the Nether. */
export const NETHER_FOG = Object.freeze([0.23, 0.05, 0.04]);
export const NETHER_MIN_LIGHT = 0.3;
/** Fog distance in the Nether (blocks): thick, warm haze, like Java. */
export const NETHER_FOG_NEAR = 10;
export const NETHER_FOG_FAR = 56;
/** Portal: interior 2..21 wide and 3..21 tall inside an obsidian frame (Java). */
export const PORTAL_MIN_W = 2, PORTAL_MIN_H = 3, PORTAL_MAX = 21;
/** Ticks the child stands in a portal before travelling. */
export const PORTAL_TICKS_CREATIVE = 4;      // walking in is enough (Java creative is instant)
export const PORTAL_TICKS_SURVIVAL = 50;      // stand still in it for 2.5 s
/** How far around the destination an existing portal is reused (blocks, x/z). */
export const PORTAL_SEARCH = 16;

/** Is world x inside the Nether strip? */
export function isNetherX(x) { return x >= NETHER_EDGE; }
/** Is column cx inside the Nether strip? */
export function isNetherColumn(cx) { return cx * 16 >= NETHER_EDGE; }
/** Overworld block (x, z) -> the Nether block it links to. */
export function toNether(x, z) { return { x: NETHER_X0 + Math.floor(x / NETHER_SCALE), z: Math.floor(z / NETHER_SCALE) }; }
/** Nether block (x, z) -> the overworld block it links to. */
export function toOverworld(x, z) { return { x: (Math.floor(x) - NETHER_X0) * NETHER_SCALE, z: Math.floor(z) * NETHER_SCALE }; }
