// OWNER: LEAD (test harness). Lanes do NOT edit this file: each lane adds scenarios in its OWN file
// tools/scenarios/<lane>.mjs (export default [ {name, requires, run}, ... ]) which is loaded automatically.
// Scenario names must be unique across all files (prefix them with the lane, e.g. 'mobs-breeding').
//
// Builds the game (dev, into .tmp/smoke-build[-tag]) unless --file/--no-build, opens it in real headless
// Chrome via Playwright, drives it through window.__game (src/core/testapi.js), saves screenshots to
// .tmp/smoke-[tag-]<scenario>.png and a JSON report to .tmp/smoke-report[-tag].json.
//
//   node tools/smoke.mjs                       all scenarios, file:// URL
//   node tools/smoke.mjs --scenario boot,world --tag corec
//   node tools/smoke.mjs --http                serve over http://127.0.0.1 (service worker path)
//   node tools/smoke.mjs --swiftshader         CPU WebGL (weak-laptop proxy; perf numbers are relative)
//   node tools/smoke.mjs --touch               touch emulation (hasTouch) + touch scenarios
//   node tools/smoke.mjs --strict              "pending" (lane still a stub) counts as failure
//   node tools/smoke.mjs --file path/index.html --no-build --headed --list --timeout 90000
//
// Status per scenario: PASS | FAIL | PENDING (a required lane is still a stub; see core/stubs.js) | SKIP.
// Exit code 1 on any FAIL (or PENDING with --strict) or any page/console error.
import { chromium } from 'playwright';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from '../build.mjs';
import { startServer } from './serve.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TMP = join(ROOT, '.tmp');
const CHROME = process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
/** Console noise that is not a game error. Keep this list tiny and specific. */
const IGNORE_CONSOLE = [/GPU stall due to ReadPixels/i, /CONTEXT_LOST_WEBGL/i, /WebGL context was lost/i];

/* ------------------------------------------------------------------ args */
function parseArgs(argv) {
  const a = { file: null, out: null, build: true, swiftshader: false, touch: false, scenarios: null, strict: false, headed: false, http: false, tag: '', list: false, timeout: 60000 };
  for (let i = 0; i < argv.length; i++) {
    const k = argv[i];
    const val = () => argv[++i];
    if (k === '--file') { a.file = resolve(ROOT, val()); a.build = false; }
    else if (k === '--out') a.out = resolve(ROOT, val());
    else if (k === '--no-build') a.build = false;
    else if (k === '--swiftshader') a.swiftshader = true;
    else if (k === '--touch') a.touch = true;
    else if (k === '--scenario' || k === '--scenarios') a.scenarios = val().split(',').map((s) => s.trim()).filter(Boolean);
    else if (k === '--strict') a.strict = true;
    else if (k === '--headed') a.headed = true;
    else if (k === '--http') a.http = true;
    else if (k === '--tag') a.tag = val();
    else if (k === '--list') a.list = true;
    else if (k === '--timeout') a.timeout = Number(val());
    else throw new Error(`smoke.mjs: unknown argument ${k}`);
  }
  return a;
}

class Pending extends Error {}

/* ------------------------------------------------------------------ scenarios
 * { name, requires: [stub names that must be implemented], touchOnly?, run: async (t) => void }
 * t.call(method, ...args)  -> window.__game[method](...args)
 *                            (t.call('waitFor', 'src expression', ms) polls the expression from Node: the page CSP
 *                            blocks compiling strings inside the page; `api` and `game` are in scope)
 * t.eval(fn, arg)          -> page.evaluate(fn, arg)
 * t.waitFor(fn, arg, ms)   -> poll page.evaluate(fn, arg) every 50 ms until truthy; resolves true / false
 * t.assert(cond, msg) / t.shot(name) / t.log(msg) / t.pending(reason) / t.note(key, value) / t.args
 */
const FLAT = { preset: 'flat', seed: 1, mode: 'creative', difficulty: 'peaceful' };

export const SCENARIOS = [
  {
    name: 'boot', requires: [],
    async run(t) {
      const state = await t.call('state');
      t.assert(state === 'title', `expected title state, got ${state}`);
      t.assert(await t.call('uiOpen') === 'title', 'title screen should be open');
      const canvas = await t.eval(() => { const c = document.getElementById('game-canvas'); return { w: c.width, h: c.height }; });
      t.assert(canvas.w > 0 && canvas.h > 0, 'canvas has a size');
      const s = await t.call('stats');
      t.note('gpu', s.gpu);
      t.note('textureLayers', s.textureLayers);
      t.note('bootMs', await t.eval(() => Math.round(window.__game.game.bootMs)));
      if (t.args.http) {
        const sw = await t.eval(async () => { for (let i = 0; i < 30; i++) { const r = await navigator.serviceWorker.getRegistration(); if (r) return true; await new Promise((x) => setTimeout(x, 100)); } return false; });
        t.assert(sw, 'service worker registered over http');
      } else {
        t.assert(await t.eval(() => location.protocol) === 'file:', 'file:// run');
      }
      await t.shot('title');
    },
  },
  {
    name: 'world', requires: [],
    async run(t) {
      const t0 = Date.now();
      await t.call('startWorld', { preset: 'default', seed: 12345, mode: 'creative', difficulty: 'peaceful' });
      t.note('worldReadyMs', Date.now() - t0);
      t.assert(await t.call('state') === 'playing', 'state should be playing');
      const s = await t.call('stats');
      t.assert(s.chunksLoaded >= 9, `expected >= 9 columns loaded, got ${s.chunksLoaded}`);
      const p = await t.call('pos');
      t.assert(p.y > 0 && p.y < 128, `player y in world (${p.y})`);
      await t.call('waitFrames', 10);
      await t.shot('world');
    },
  },
  {
    name: 'terrain-render', requires: ['textures', 'worldgen', 'world', 'lighting', 'mesher', 'renderer'],
    async run(t) {
      await t.call('startWorld', { preset: 'default', seed: 12345, mode: 'creative' });
      await t.call('setLook', 30, -20);
      await t.call('waitFrames', 30);
      const s = await t.call('stats');
      t.note('stats', s);
      t.assert(s.drawCalls > 0, 'draw calls > 0');
      t.assert(s.triangles > 1000, `triangles > 1000 (got ${s.triangles})`);
      const px = await t.call('pixelStats');
      t.note('pixels', px);
      t.assert(px.uniqueColors > 40 && px.stdLuma > 8, `screen is not blank (${JSON.stringify(px)})`);
      await t.shot('terrain');
      await t.call('setTime', 18000);
      await t.call('waitFrames', 5);
      const night = await t.call('pixelStats');
      t.assert(night.meanLuma < px.meanLuma, 'night is darker than day');
      await t.shot('terrain-night');
      await t.call('setTime', 6000);
    },
  },
  {
    name: 'move-jump', requires: ['input', 'player', 'physics', 'world', 'worldgen'],
    async run(t) {
      await t.call('startWorld', FLAT);
      await t.call('setFlying', false);
      await t.call('waitTicks', 20);
      let p = await t.call('pos');
      t.assert(p.onGround, `player on ground after spawn (${JSON.stringify(p)})`);
      t.assert(Math.abs(p.y - 4) < 0.01, `flat world feet y = 4 (got ${p.y})`);
      await t.call('setLook', 0, 0);
      const before = p;
      p = await t.call('move', 1, 0, 1000);
      const dist = Math.hypot(p.x - before.x, p.z - before.z);
      t.note('walk1s', dist);
      t.assert(dist > 3.0 && dist < 5.0, `walked ~4.3 blocks in 1 s (got ${dist.toFixed(2)})`);
      t.assert(p.z < before.z, 'forward at yaw 0 moves toward -Z (north)');
      const y0 = p.y;
      await t.call('jump');
      let maxY = y0;
      for (let i = 0; i < 12; i++) { await t.call('waitTicks', 1); maxY = Math.max(maxY, (await t.call('pos')).y); }
      t.note('jumpHeight', maxY - y0);
      t.assert(maxY - y0 > 1.15 && maxY - y0 < 1.35, `jump apex ~1.25 (got ${(maxY - y0).toFixed(3)})`);
      await t.call('waitTicks', 20);
      p = await t.call('pos');
      t.assert(p.onGround && Math.abs(p.y - y0) < 0.01, 'landed again');
    },
  },
  {
    name: 'break-place', requires: ['input', 'player', 'physics', 'raycast', 'interaction', 'world'],
    async run(t) {
      await t.call('startWorld', FLAT);
      await t.call('setFlying', false);
      await t.call('waitTicks', 10);
      await t.call('setLook', 0, -55);
      await t.call('waitFrames', 3);
      const tg = await t.call('target');
      t.assert(tg && tg.name === 'grass_block', `targets the grass in front (${JSON.stringify(tg)})`);
      const br = await t.call('breakTarget');
      t.note('break', br);
      t.assert(br.ok && br.after === 'air', `block broken (${JSON.stringify(br)})`);
      t.assert(await t.call('eventCount', 'block:broken') >= 1, 'block:broken emitted');
      await t.call('setLook', 0, -55);
      await t.call('selectSlot', 1);
      const sel = await t.call('selected');
      t.assert(sel.item === 'oak_planks', `slot 2 holds planks (${sel.item})`);
      const pl = await t.call('placeTarget');
      t.note('place', pl);
      t.assert(pl.ok && pl.placed === 'oak_planks', `placed planks (${JSON.stringify(pl)})`);
      await t.shot('break-place');
    },
  },
  {
    name: 'hotbar', requires: [],
    async run(t) {
      await t.call('startWorld', FLAT);
      await t.call('selectSlot', 4);
      const s = await t.call('selected');
      t.assert(s.slot === 4, 'slot 5 selected');
      t.assert(s.item === 'red_wool', `kid hotbar slot 5 is red wool (${s.item})`);
      const left = await t.call('give', 'diamond', 10);
      t.assert(left === 0, 'diamonds fit');
      const inv = await t.call('inventory');
      t.assert(inv.some((x) => x && x.item === 'diamond' && x.count === 10), 'diamonds in inventory');
      t.assert(await t.call('eventCount', 'player:hotbar') >= 1, 'player:hotbar emitted');
    },
  },
  {
    name: 'inventory-ui', requires: [],
    async run(t) {
      await t.call('startWorld', FLAT);
      const open = await t.call('openInventory');
      t.assert(open === 'creative', `creative picker opens in creative (got ${open})`);
      await t.shot('inventory');
      const closed = await t.call('closeUI');
      t.assert(closed === null, 'closed');
      await t.call('setMode', 'survival');
      t.assert(await t.call('openInventory') === 'inventory', 'survival inventory opens in survival');
      await t.call('closeUI');
      await t.call('setMode', 'creative');
    },
  },
  {
    name: 'time', requires: [],
    async run(t) {
      await t.call('startWorld', FLAT);
      t.assert(await t.call('getTime') === 3000, 'kid worlds start at 09:00 (3000)');
      await t.call('waitTicks', 20);
      t.assert(await t.call('getTime') === 3000, 'time is locked by default');
      t.assert(await t.call('setTime', 18000) === 18000, 'setTime works');
      await t.call('waitFrames', 3);
      await t.shot('night');
      await t.call('setTime', 3000);
    },
  },
  {
    name: 'kid-home', requires: [],
    async run(t) {
      await t.call('startWorld', FLAT);
      const home = await t.call('pos');
      await t.call('teleport', home.x + 40, home.y + 10, home.z + 40);
      await t.eval(() => window.__game.game.events.emit('input:action', { action: 'home', down: true, source: 'test' }));
      await t.call('waitTicks', 5);
      const p = await t.call('pos');
      t.assert(Math.hypot(p.x - home.x, p.z - home.z) < 2, `home brings the player back (${JSON.stringify(p)})`);
    },
  },
  {
    name: 'mobs', requires: ['mobs', 'physics', 'world'],
    async run(t) {
      await t.call('startWorld', FLAT);
      const p = await t.call('pos');
      const id = await t.call('spawn', 'pig', p.x + 3, p.y, p.z - 3);
      t.assert(id !== null, 'pig spawned');
      await t.call('waitTicks', 60);
      const pig = (await t.call('entities')).find((e) => e.id === id);
      t.assert(pig && pig.y >= 3.99 && pig.y < 5, `pig stands on the flat ground (${JSON.stringify(pig)})`);
      await t.call('setLook', -45, -20);
      await t.call('waitFrames', 5);
      await t.shot('mobs');
    },
  },
  {
    name: 'survival-fall', requires: ['survival', 'player', 'physics'],
    async run(t) {
      await t.call('startWorld', { ...FLAT, mode: 'survival', difficulty: 'easy' });
      await t.call('setRule', 'fallDamage', true);
      const p = await t.call('pos');
      await t.call('teleport', p.x, p.y + 10, p.z);
      await t.call('waitTicks', 60);
      const q = await t.call('pos');
      t.assert(q.health <= 13 && q.health >= 12, `10-block fall costs 7 HP (health ${q.health})`);
    },
  },
  {
    name: 'save-load', requires: ['save', 'world'],
    async run(t) {
      await t.call('startWorld', FLAT);
      const p = await t.call('pos');
      const bx = Math.floor(p.x) + 2, bz = Math.floor(p.z) + 2;
      t.assert(await t.call('setBlock', bx, 4, bz, 'gold_block'), 'block set');
      const meta = await t.call('meta');
      t.assert(await t.call('save'), 'saved');
      await t.call('exitToTitle');
      const worlds = await t.call('listWorlds');
      t.assert(worlds.some((w) => w.id === meta.id), 'world listed');
      await t.eval(async (id) => { const g = window.__game.game; const d = await g.save.loadWorld(id); await g.startWorld(d); }, meta.id);
      t.assert(await t.call('getBlock', bx, 4, bz) === 'gold_block', 'block persisted');
    },
  },
  {
    name: 'touch-controls', requires: ['touch', 'input'], touchOnly: true,
    async run(t) {
      await t.call('startWorld', FLAT);
      await t.page.touchscreen.tap(640, 300);
      await t.call('waitFrames', 5);
      const visible = await t.eval(() => window.__game.game.touch.visible);
      t.assert(visible, 'touch controls appear after a touch');
      await t.shot('touch');
    },
  },
  {
    name: 'context-loss', requires: ['renderer'],
    async run(t) {
      if (!(await t.call('worldReadyNow'))) await t.call('startWorld', FLAT);
      t.assert(await t.call('contextLossTest'), 'context loss/restore ran');
      const f0 = (await t.call('stats')).frames;
      await t.call('waitFrames', 10);
      t.assert((await t.call('stats')).frames > f0, 'frames continue after restore');
      const px = await t.call('pixelStats');
      t.assert(px.uniqueColors > 10, 'still rendering after restore');
    },
  },
  {
    name: 'perf', requires: [],
    async run(t) {
      await t.call('startWorld', { preset: 'default', seed: 777, mode: 'creative' });
      await t.call('setLook', 0, -10);
      await t.call('setFlying', true);
      const before = await t.call('stats');
      await t.call('move', 1, 0, 3000);
      const s = await t.call('stats');
      t.note('stats', s);
      t.assert(s.frames > before.frames, 'frames advance');
      t.assert(s.fps > 0, 'fps measured');
      if (!t.stubs.includes('renderer')) t.assert(s.drawCalls <= 1000, `draw calls bounded (${s.drawCalls})`);
    },
  },
];

/* ------------------------------------------------------------------ runner */
async function loadScenarioFiles() {
  const dir = join(ROOT, 'tools', 'scenarios');
  if (!existsSync(dir)) return;
  for (const f of readdirSync(dir).filter((x) => x.endsWith('.mjs')).sort()) {
    const mod = await import(pathToFileURL(join(dir, f)).href);
    const list = mod.default || mod.SCENARIOS || [];
    for (const s of list) {
      if (!s || !s.name || typeof s.run !== 'function') throw new Error(`tools/scenarios/${f}: scenario needs {name, requires, run}`);
      if (SCENARIOS.some((x) => x.name === s.name)) throw new Error(`tools/scenarios/${f}: duplicate scenario name ${s.name}`);
      SCENARIOS.push({ requires: [], ...s, file: f });
    }
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  await loadScenarioFiles();
  if (args.list) { for (const s of SCENARIOS) console.log(`${s.name.padEnd(16)} requires: ${s.requires.join(', ') || '-'}${s.touchOnly ? ' (touch only)' : ''}`); return 0; }
  mkdirSync(TMP, { recursive: true });
  const tagp = args.tag ? args.tag + '-' : '';

  let file = args.file;
  if (!file) {
    const out = args.out || join(TMP, 'smoke-build' + (args.tag ? '-' + args.tag : ''));
    if (args.build) await build({ dev: true, out, quiet: false });
    file = join(out, 'index.html');
  }
  if (!existsSync(file)) throw new Error(`no build at ${file} (run without --no-build)`);
  if (!existsSync(CHROME)) throw new Error(`Chrome not found at ${CHROME} (set CHROME_PATH)`);

  let server = null, url;
  if (args.http) { server = await startServer({ port: 0, dir: dirname(file), quiet: true }); url = server.url + 'index.html'; }
  else url = pathToFileURL(file).href;

  const launchArgs = ['--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-backgrounding-occluded-windows', '--autoplay-policy=no-user-gesture-required'];
  if (args.swiftshader) launchArgs.push('--use-angle=swiftshader', '--enable-unsafe-swiftshader');
  const browser = await chromium.launch({ executablePath: CHROME, headless: !args.headed, args: launchArgs });
  const context = await browser.newContext({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: 1, hasTouch: args.touch });
  const page = await context.newPage();
  const pageErrors = [];
  page.on('pageerror', (e) => pageErrors.push(`pageerror: ${e.message}`));
  page.on('console', (m) => {
    if (m.type() === 'error' && !IGNORE_CONSOLE.some((r) => r.test(m.text()))) pageErrors.push(`console.error: ${m.text()}`);
  });
  page.on('crash', () => pageErrors.push('page crashed'));

  const results = [];
  let stubs = [];
  const t0 = Date.now();
  try {
    await page.goto(url, { waitUntil: 'load', timeout: 30000 });
    await page.waitForFunction(() => window.__game && window.__game.ready === true, null, { timeout: 30000 });
    stubs = await page.evaluate(() => window.__game.stubs());
    console.log(`[smoke] ${url}`);
    console.log(`[smoke] stub lanes: ${stubs.length ? stubs.join(' ') : '(none)'}`);

    const selected = SCENARIOS.filter((s) => !args.scenarios || args.scenarios.includes(s.name));
    if (args.scenarios) for (const n of args.scenarios) if (!SCENARIOS.some((s) => s.name === n)) throw new Error(`unknown scenario ${n}`);
    for (const s of selected) {
      const r = { name: s.name, status: 'PASS', ms: 0, notes: {}, error: null };
      const started = Date.now();
      const missing = s.requires.filter((x) => stubs.includes(x));
      if (s.touchOnly && !args.touch) { r.status = 'SKIP'; r.error = 'needs --touch'; results.push(r); continue; }
      if (missing.length) {
        r.status = args.strict ? 'FAIL' : 'PENDING';
        r.error = `stub lanes: ${missing.join(', ')}`;
        results.push(r);
        continue;
      }
      const t = makeCtx(page, s.name, tagp, r, stubs, args);
      try {
        await withTimeout(s.run(t), args.timeout, s.name);
        const errs = await page.evaluate(() => window.__game.errors.map((e) => `${e.where}: ${e.message}`));
        if (errs.length) throw new Error(`game errors: ${errs.join(' | ')}`);
      } catch (err) {
        if (err instanceof Pending) { r.status = args.strict ? 'FAIL' : 'PENDING'; r.error = err.message; }
        else {
          r.status = 'FAIL'; r.error = err && err.message ? err.message : String(err);
          try { await page.screenshot({ path: join(TMP, `smoke-${tagp}${s.name}-FAIL.png`) }); } catch { /* ignore */ }
        }
      }
      r.ms = Date.now() - started;
      results.push(r);
      // leave the game at the title between scenarios that started worlds
      try { await page.evaluate(async () => { if (window.__game.game.meta) await window.__game.exitToTitle(); window.__game.game.errors.length = 0; }); } catch { /* ignore */ }
    }
  } catch (err) {
    results.push({ name: 'harness', status: 'FAIL', ms: 0, notes: {}, error: err && err.message ? err.message : String(err) });
  } finally {
    await browser.close().catch(() => {});
    if (server) await server.close();
  }

  if (pageErrors.length) results.push({ name: 'page-errors', status: 'FAIL', ms: 0, notes: {}, error: pageErrors.slice(0, 20).join('\n') });
  else results.push({ name: 'page-errors', status: 'PASS', ms: 0, notes: {}, error: null });

  console.log('');
  for (const r of results) {
    const notes = Object.keys(r.notes).length ? ' ' + JSON.stringify(r.notes) : '';
    console.log(`${r.status.padEnd(8)} ${r.name.padEnd(16)} ${String(r.ms).padStart(6)} ms${r.error ? '  - ' + r.error : ''}${notes}`);
  }
  const counts = results.reduce((a, r) => ((a[r.status] = (a[r.status] || 0) + 1), a), {});
  const failed = results.some((r) => r.status === 'FAIL');
  console.log(`\n[smoke] ${JSON.stringify(counts)} in ${((Date.now() - t0) / 1000).toFixed(1)} s${args.swiftshader ? ' (swiftshader)' : ''}${args.touch ? ' (touch)' : ''}`);
  writeFileSync(join(TMP, `smoke-report${args.tag ? '-' + args.tag : ''}.json`), JSON.stringify({ when: new Date().toISOString(), url, args, stubs, results }, null, 2));
  return failed ? 1 : 0;
}

function makeCtx(page, name, tagp, r, stubs, args) {
  return {
    page, stubs, args,
    call: (method, ...a) => {
      if (method === 'waitFor' && typeof a[0] === 'string') return pollExpression(page, a[0], a[1] ?? 5000);
      return page.evaluate(async ({ method, a }) => {
        const api = window.__game;
        if (method === 'worldReadyNow') return api.worldReady;
        if (typeof api[method] !== 'function') throw new Error(`__game.${method} is not a function`);
        return await api[method](...a);
      }, { method, a });
    },
    eval: (fn, arg) => page.evaluate(fn, arg),
    waitFor: async (fn, arg, ms = 5000) => {
      const end = Date.now() + ms;
      while (Date.now() < end) { if (await page.evaluate(fn, arg)) return true; await new Promise((r) => setTimeout(r, 50)); }
      return false;
    },
    assert(cond, msg) { if (!cond) throw new Error(`assert: ${msg}`); },
    pending(reason) { throw new Pending(reason); },
    note(k, v) { r.notes[k] = v; },
    log: (m) => console.log(`  [${name}] ${m}`),
    shot: (n) => page.screenshot({ path: join(TMP, `smoke-${tagp}${n}.png`) }),
  };
}

/** Poll a source expression (api = window.__game, game = api.game in scope) from Node: CSP-proof. */
async function pollExpression(page, src, ms) {
  const expr = `(() => { const api = window.__game, game = api.game; try { return !!(${src}); } catch (e) { return false; } })()`;
  const end = Date.now() + ms;
  while (Date.now() < end) { if (await page.evaluate(expr)) return true; await new Promise((r) => setTimeout(r, 50)); }
  return false;
}

function withTimeout(p, ms, name) {
  let to;
  return Promise.race([p, new Promise((_, rej) => { to = setTimeout(() => rej(new Error(`timeout after ${ms} ms in ${name}`)), ms); })]).finally(() => clearTimeout(to));
}

main().then((code) => process.exit(code), (err) => { console.error('[smoke] harness error:', err); process.exit(1); });
